[project]
name = "real-esrgan"
version = "0.3.1"
description = ""
readme = "README.md"
requires-python = "==3.10.*"
dependencies = [
    'patch_ng',
    'basicsr',
    'facexlib==0.3.*',
    'gfpgan==1.*',
    'opencv-contrib-python',
    'ffmpeg-python',
    'Pillow',
    'torch>=2.0',
    'torchvision',
    'tqdm',
    'wget',
    "lightning==2.*",
]

[dependency-groups]
dev = ["cog==0.13.*"]

[tool.uv.sources]
torch = [
    { index = 'pytorch-cu118', marker = "sys_platform == 'linux' or sys_platform == 'win32'"}
]
torchvision = [
    { index = 'pytorch-cu118', marker = "sys_platform == 'linux' or sys_platform == 'win32'"}
]
basicsr = [
    # fixed for `pytorch>=2.0`, but never pushed to pypi
    { git = "https://github.com/XPixelGroup/BasicSR", rev = "8d56e3a045f9fb3e1d8872f92ee4a4f07f886b0a" }
]

[[tool.uv.index]]
name = 'pytorch-cu118'
url = 'https://download.pytorch.org/whl/cu118'
explicit = true


[tool.pyright]
include = ['src']
